/*
 * DESTA PLAY — LIVE GAME VOICE
 *
 * Voice is generated by the device/browser speech engine.
 * No bundled number recordings and no external TTS service are used.
 *
 * Rules:
 *   BINGO  → LETTER + NUMBER (B 12, G 47, O 71)
 *   KENO   → NUMBER ONLY (12, 47, 71)
 *
 * The number is accepted only from the server-authoritative round state.
 * The same engine is used by the real room and Watch Live.
 */
const DestaVoice = (() => {
  let activeGame = null;
  let activeRoundId = null;
  let activeStake = null;
  let enabled = false;
  let speaking = false;
  let lastAnnouncementKey = null;
  let queue = [];
  let playGeneration = 0;

  const MAX_QUEUE = 8;

  function synth() {
    return typeof window !== "undefined" && window.speechSynthesis
      ? window.speechSynthesis
      : null;
  }

  function getBingoLetter(number) {
    number = Number(number);
    if (!Number.isInteger(number)) return null;
    if (number >= 1 && number <= 15) return "B";
    if (number >= 16 && number <= 30) return "I";
    if (number >= 31 && number <= 45) return "N";
    if (number >= 46 && number <= 60) return "G";
    if (number >= 61 && number <= 75) return "O";
    return null;
  }

  function buildAnnouncement(game, number, language = "en") {
    game = String(game || "").toLowerCase();
    number = Number(number);
    const lang = String(language || "en").toLowerCase() === "am" ? "am" : "en";

    if (!Number.isInteger(number)) return null;

    if (game === "bingo") {
      const letter = getBingoLetter(number);
      if (!letter) return null;

      if (lang === "am") {
        // Spoken Amharic equivalents of the B-I-N-G-O column letters.
        const am = { B: "ቢ", I: "አይ", N: "ኤን", G: "ጂ", O: "ኦ" };
        return `${am[letter]} ${number}`;
      }

      return `${letter} ${number}`;
    }

    if (game === "keno" && number >= 1 && number <= 80) {
      return String(number);
    }

    return null;
  }

  function stopSpeech() {
    const s = synth();
    if (!s) return;
    try { s.cancel(); } catch (_) {}
    try { s.resume(); } catch (_) {}
  }

  function stopVoice() {
    queue = [];
    speaking = false;
    playGeneration++;
    stopSpeech();
  }

  function enterLiveGame(game, roundId, stake) {
    stopVoice();
    activeGame = String(game || "").toLowerCase();
    activeRoundId = roundId == null ? null : String(roundId);
    activeStake = stake == null ? null : Number(stake);
    lastAnnouncementKey = null;
  }

  function leaveLiveGame() {
    stopVoice();
    activeGame = null;
    activeRoundId = null;
    activeStake = null;
    lastAnnouncementKey = null;
  }

  function isActive(game, roundId, stake) {
    game = String(game || "").toLowerCase();
    if (activeGame !== game) return false;
    if (activeRoundId !== null && roundId != null && String(activeRoundId) !== String(roundId)) return false;
    if (activeStake !== null && stake != null && Number(activeStake) !== Number(stake)) return false;
    return true;
  }

  function getVoices() {
    const s = synth();
    if (!s || typeof s.getVoices !== "function") return [];
    try { return s.getVoices() || []; } catch (_) { return []; }
  }

  function chooseVoice(language) {
    const wanted = language === "am" ? "am" : "en";
    const voices = getVoices();
    if (!voices.length) return null;

    const exact = voices.find(v => String(v.lang || "").toLowerCase() === (wanted === "am" ? "am-et" : "en-us"));
    if (exact) return exact;

    const family = voices.find(v => String(v.lang || "").toLowerCase().startsWith(wanted));
    if (family) return family;

    if (wanted === "en") {
      return voices.find(v => String(v.lang || "").toLowerCase().startsWith("en")) || null;
    }

    // Keep Amharic language requested even when the device exposes no named
    // Amharic voice; the browser can still route am-ET to its installed TTS.
    return null;
  }

  function speakNow(item, generation) {
    const s = synth();
    if (!s || !enabled || generation !== playGeneration) {
      speaking = false;
      return false;
    }

    const text = String(item.text || "").trim();
    if (!text) {
      speaking = false;
      return false;
    }

    try {
      const utterance = new SpeechSynthesisUtterance(text);
      const language = item.language === "am" ? "am" : "en";
      const voice = chooseVoice(language);

      utterance.lang = language === "am" ? "am-ET" : "en-US";
      if (voice) utterance.voice = voice;
      utterance.rate = 0.88;
      utterance.pitch = 1;
      utterance.volume = 1;

      utterance.onend = () => {
        if (generation !== playGeneration) return;
        speaking = false;
        playNext();
      };

      utterance.onerror = () => {
        if (generation !== playGeneration) return;
        speaking = false;
        playNext();
      };

      speaking = true;
      try { s.resume(); } catch (_) {}
      s.speak(utterance);
      return true;
    } catch (_) {
      speaking = false;
      return false;
    }
  }

  function playNext() {
    if (!enabled || speaking || !queue.length) return;
    const item = queue.shift();
    const generation = playGeneration;
    if (!speakNow(item, generation)) {
      speaking = false;
      if (queue.length) setTimeout(playNext, 0);
    }
  }

  function unlock() {
    const s = synth();
    if (!s) return false;
    try { s.resume(); } catch (_) {}
    // Voice playback is deliberately started by the caller's user gesture.
    return true;
  }

  function speakText(text, language = "en") {
    if (!enabled || !String(text || "").trim()) return false;
    queue.unshift({
      text: String(text),
      language: String(language || "en").toLowerCase() === "am" ? "am" : "en"
    });
    if (queue.length > MAX_QUEUE) queue.length = MAX_QUEUE;
    playNext();
    return true;
  }

  function announceDraw({ game, roundId, stake, number, language = "en" }) {
    game = String(game || "").toLowerCase();
    number = Number(number);
    const lang = String(language || "en").toLowerCase() === "am" ? "am" : "en";

    if (!enabled || !isActive(game, roundId, stake)) return false;

    if (game === "bingo" && (!Number.isInteger(number) || number < 1 || number > 75)) return false;
    if (game === "keno" && (!Number.isInteger(number) || number < 1 || number > 80)) return false;

    const text = buildAnnouncement(game, number, lang);
    if (!text) return false;

    const key = `${game}:${roundId}:${stake}:${number}:${lang}`;
    if (key === lastAnnouncementKey) return false;
    lastAnnouncementKey = key;

    queue.push({ text, language: lang });
    if (queue.length > MAX_QUEUE) queue.shift();
    playNext();
    return true;
  }

  function setEnabled(value) {
    enabled = Boolean(value);
    if (!enabled) stopVoice();
    else unlock();
  }

  function toggle() {
    setEnabled(!enabled);
    return enabled;
  }

  function getState() {
    return {
      enabled,
      speaking,
      activeGame,
      activeRoundId,
      activeStake,
      supported: !!synth()
    };
  }

  if (typeof window !== "undefined") {
    window.addEventListener("pagehide", stopVoice);
    window.addEventListener("visibilitychange", () => {
      if (document.hidden) stopVoice();
    });
  }

  return {
    enterLiveGame,
    leaveLiveGame,
    announceDraw,
    buildAnnouncement,
    getBingoLetter,
    setEnabled,
    toggle,
    stopVoice,
    speakText,
    unlock,
    getState
  };
})();

if (typeof window !== "undefined") window.DestaVoice = DestaVoice;
