import BingoEngine from './BingoEngine.js';
import KenoEngine from './KenoEngine.js';
import TambolaEngine from './TambolaEngine.js';
import Bingo90Engine from './Bingo90Engine.js';
import Bingo75Engine from './Bingo75Engine.js';
import NumberDrawEngine from './NumberDrawEngine.js';
import TriviaEngine from './TriviaEngine.js';
import WheelPredictionEngine from './WheelPredictionEngine.js';
import LudoEngine from './LudoEngine.js';
import HighCardEngine from './HighCardEngine.js';
import PenaltyEngine from './PenaltyEngine.js';
import DiceEngine from './DiceEngine.js';
import TargetRushEngine from './TargetRushEngine.js';
import MemoryMatchEngine from './MemoryMatchEngine.js';
import MiniRacingEngine from './MiniRacingEngine.js';
import SpeedCardsEngine from './SpeedCardsEngine.js';
import NumberRushEngine from './NumberRushEngine.js';
export const PVP_ENGINES={bingo:BingoEngine,keno:KenoEngine,tambola:TambolaEngine,bingo90:Bingo90Engine,bingo75:Bingo75Engine,numberdraw:NumberDrawEngine,trivia:TriviaEngine,wheel:WheelPredictionEngine,ludo:LudoEngine,highcard:HighCardEngine,penalty:PenaltyEngine,dice:DiceEngine,target:TargetRushEngine,memory:MemoryMatchEngine,racing:MiniRacingEngine,speedcards:SpeedCardsEngine,numberrush:NumberRushEngine};
export default PVP_ENGINES;
